/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: aa@bb.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	dbservice "ambulance-webapi/db-service"
	router "ambulance-webapi/router"
	"log"
)

func main() {
	log.Printf("Server started")

	dbservice.Connect()
	defer dbservice.Disconnect()

	router := router.NewRouter()

	log.Fatal(router.Run(":8080"))
}
