name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Go version 1.19
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
        
    - name: Build Go project
      run: go build
      
    - name: Run the tests
      run: go test ./...
  
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Docker build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          sevcikmichal/microfrontends-webcomponent-webapi-sample:1.0.0-${{ github.run_number }}
          sevcikmichal/microfrontends-webcomponent-webapi-sample:latest
          sevcikmichal/microfrontends-webcomponent-webapi-sample:dev-latest
